### ISSUE TITLE
createToken Method Missing

### ISSUE THREAD

**Issue by tiago-gomes** [crabstudio/app#1]
Hi crabstudio.

I just found a missing method, can you commit the method?
Thanks

2016-07-15 05:15:44 Error: [BadMethodCallException] Unknown method "createToken"
Request URL: /crabapp/admin/lost-password
Referer URL: http://127.0.0.1/crabapp/admin/lost-password
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/crabapp/src/Controller/Admin/UsersController.php(324): Cake\ORM\Table->__call('createToken', Array)
#1 /var/www/html/crabapp/src/Controller/Admin/UsersController.php(324): App\Model\Table\UsersTable->createToken('geone85@gmail.c...', true, '24 hours')
#2 [internal function]: App\Controller\Admin\UsersController->lostPassword()
#3 /var/www/html/crabapp/vendor/cakephp/cakephp/src/Controller/Controller.php(429): call_user_func_array(Array, Array)
#4 /var/www/html/crabapp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#5 /var/www/html/crabapp/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\Admin\UsersController))
#6 /var/www/html/crabapp/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 {main}

**Comment by anhtuank7c** [comment]
Ensure that you get the latest package version **3.2.8**: (remove downloaded composer package if exist)

```
composer self-update
composer create-project --prefer-dist crabstudio/app demo
```

The **createToken** method located [here](https://github.com/crabstudio/app/blob/3.2.8/src/Model/Table/UsersTable.php#L239)

**Comment by anhtuank7c** [comment]
@tiago-gomes Can we close this issue?
