### ISSUE TITLE
Upload file error

### ISSUE THREAD

**Issue by paul-phan** [crabstudio/app#2]
Hi, went I want to upload a file, in template I make add/edit like this: 
 echo $this->Form->input('avatar', ['type' => 'file']);

but went I click to upload button it redirect to 
http://localhost/filemanager/dialog.php?type=1&relative_url=1&field_id=avatar
Then it will show Object not found!
Error 404 page.
If I add projectname between localhost/ and /filemanager it will show normaly.
I think the base_path is missing from filemanager... please fix...

**Comment by anhtuank7c** [comment]
@gangstara2 You should run Application in the shell.

```
bin/cake server
```

Application will listen on default port `8765`

Then go to `http://localhost:8765/your/page/add` and try to upload again.

I guess you was run application in `xampp` or `wamp` etc... and the path to the file manager is relative path `/filemanager...`

**Comment by paul-phan** [comment]
It's seem work well now when I start server http://localhost:8765/ but I have another qs:
After I upload avatar to http://localhost:8765/filemanager/dialog.php?type=1&relative_url=1&field_id=avatar, how I can go back and I want the echo $this->Form->input('avatar', ['type' => 'file']); to be filled by the url to file path. Or I need to copy the file path then paste it :( ?

**Comment by anhtuank7c** [comment]
You can learn it from `localhost:8765/admin/setting`

The logo field was implemented widget `check the code to learn more`
